version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - my_db_data:/var/lib/postgresql/data

#  bot:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: funnel_bot
#    env_file:
#      - .env
#    depends_on:
#      - postgres
#    restart: always
#    command: [ "/app/docker/wait_for_it.sh postgres && alembic upgrade head && python -m src.bot" ]

volumes:
  my_db_data: